### PR TITLE
Update contract.ts

### PR DESCRIPTION
**Pull request by Jeban11**
Check my project structure and flow

### CODE REVIEW

**Comment by Jeyandh** [comment]
Hi Jeban, I check your front end file in that i saw that you have not follow the coding standard for variables in contract.ts.

**Comment by Jeban11** [comment]
Ok Jeyanth ,I will check

**Comment by Jeban11** [comment]
Hi Jeyanth,I changed you mentioned above .Kindly check it.

**Comment by Jeyandh** [comment]
There is no other changes Jeban. Thank you.

**Comment by Jeban11** [comment]
Thank you Jeyanthan

**Pull request merged**
